### ISSUE TITLE
Podcast Button Choices

### ISSUE THREAD

**Issue by manno** [voc/media-frontend#26]
The podcast button links to the feed for the last two years. An often requested feature are conference feeds, which actually exists, but are not displayed.

The following feeds exist:

* C3TV - News
* C3TV - RSS, last 100
* C3TV - Podcast feed of the last two years
* C3TV - Podcast archive feed
* Podcast feed for this folder

**Comment by saerdnaer** [comment]
The Podcast-Feed icon in the header has now a dropdown option:
![temp](https://cloud.githubusercontent.com/assets/40266/11545757/557a569c-9949-11e5-96ac-a5a61284db66.png)
