### ISSUE TITLE
Klickable Authors on event page

### ISSUE THREAD

**Issue by derpeter** [voc/media-frontend#35]
On event pages like http://media.ccc.de/browse/broadcast/chaosradio/cr209.html#video only the whole list of speakers is klickable not each speaker. This makes the search useless as long as this group of speakers is always working together.

**Comment by saerdnaer** [comment]
@meise how difficult is it to remove the space before the comma?
Currently the output is ```Marcus Richter , danimo , erdgeist , Lasse and Matthias Kirschner```, if possible it should be ``` Marcus Richter, danimo, erdgeist, Lasse and Matthias Kirschner```

**Comment by optikfluffel** [comment]
Haml has a little [helper method called `succeed`](http://haml.info/docs/yardoc/file.REFERENCE.html#succeed) for this kind of stuff.
