### ISSUE TITLE
Generate audio podcast feeds containing all new content.

### ISSUE THREAD

**Issue by ypid** [voc/media-frontend#43]
I would like to suggest that you generate along with the https://media.ccc.de/podcast.xml feed some audio only feeds like https://media.ccc.de/podcast-opus.xml and https://media.ccc.de/podcast-mp3.xml. About the size I am thinking as those feeds are probably subscribed on mobile devices that about 6 months of content could be included and the content before using paged feeds. This would allow users to subscribe to the feed once and see about all new content on audio podcachers.

See: https://github.com/cccc/media-webgen/issues/3#issuecomment-138260063

**Comment by saerdnaer** [comment]
Just for a note for me: We already provide podcast feeds by format (see https://events.ccc.de/congress/2014/wiki/Static:Documentation#Podcast_Feeds for example), but only for single events and not for everything.

**Comment by saerdnaer** [comment]
With the new media.ccc.de release came an audio-only feed: https://media.ccc.de/podcast-audio-only.xml

If you have further suggestions please open a new issue at https://github.com/voc/media.ccc.de/issues
